version: "3"
services:
  triton-server:
    image: nvcr.io/nvidia/tritonserver:23.02-py3
    volumes:
      - ${REPO_PATH}:/models
    command: sleep infinity  
    # command: tritonserver --model-repository=/models
    # command: tritonserver --model-repository=/models --model-control-mode=poll --repository-poll-secs=5
    restart: always
    network_mode: "host"

  triton-client:
    image: nvcr.io/nvidia/tritonserver:23.02-py3-sdk
    command: sleep infinity
    restart: always
    network_mode: "host"
